# Generated by Django 3.2.6 on 2021-08-02 22:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('ronin_id', models.CharField(blank=True, max_length=42, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_slp', models.PositiveIntegerField(default=0)),
                ('total_slp', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('observarion', models.TextField(blank=True, null=True)),
                ('ronin_id', models.CharField(blank=True, max_length=42, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='manager.scholarshipowner')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 8, 2, 22, 20, 51, 932862, tzinfo=utc))),
                ('tax', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('slp', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Axie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axie_id', models.CharField(max_length=50)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eth_cost', models.DecimalField(decimal_places=9, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axies', to='manager.student', validators=[manager.models.validate_axie_limit])),
            ],
        ),
    ]
